name: run-sync
on:
  schedule:
    - cron: '14 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-lanhebe-proxypool
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lanhebe-proxypool
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/lanhebe/proxypool.git"
          source_branch: "master"
          destination_branch: "DL123"
          github_token: ${{ secrets.PAT }}
